import {
  Img1,
  Img2,
  Img3,
  Img4,
  Img5,
  Img6,
  Img7,
  Img8,
  Img9,
  Img10,
  Img11,
  Img12,
  Img13,
  Img14,
  Img15,
  Img16,
  Img17,
  Img18,
  Img19,
  Img20,
  Img21,
  Img22,
  Img23,
  Img24,
  Img25,
  Img26,
  Img27,
  Img28,
  Img29,
  Img30,
  Img31,
  Img32,
  Img33,
  Img34,
  Img35,
  Img36,
  Img37,
  Img38,
  Img39,
  Img40,
  Img41,
  Img42,
} from "../assets/ProfilePictures/OurAdvocate";

export const advocateInfo = [
  {
    img1URL: Img1,
    img2URL: Img2,
    name1: "Alexander Perez",
    name2: "Floyd Miles",
    school: "Harvard",
  },
  {
    img1URL: Img3,
    img2URL: Img4,
    name1: "Courtney Henry",
    name2: "Robert Fox",
    school: "Princeton",
  },
  {
    img1URL: Img5,
    img2URL: Img6,
    name1: "Jerome Bell",
    name2: "Bessie Cooper",
    school: "Chicago",
  },
  {
    img1URL: Img7,
    img2URL: Img8,
    name1: "Eleanor Pena",
    name2: "Brooklyn Simmons",
    school: "Yale",
  },
  {
    img1URL: Img9,
    img2URL: Img10,
    name1: "Alexander Perez",
    name2: "Floyd Miles",
    school: "Harvard",
  },
  {
    img1URL: Img11,
    img2URL: Img12,
    name1: "Marvin McKinney",
    name2: "Leslie Alexander",
    school: "MIT",
  },
  {
    img1URL: Img13,
    img2URL: Img14,
    name1: "Alexander Perez",
    name2: "Floyd Miles",
    school: "Harvard",
  },
  {
    img1URL: Img15,
    img2URL: Img16,
    name1: "Marvin McKinney",
    name2: "Leslie Alexander",
    school: "MIT",
  },
  {
    img1URL: Img17,
    img2URL: Img18,
    name1: "Alexander Perez",
    name2: "Floyd Miles",
    school: "Harvard",
  },
  {
    img1URL: Img19,
    img2URL: Img20,
    name1: "Courtney Henry",
    name2: "Robert Fox",
    school: "Princeton",
  },
  {
    img1URL: Img21,
    img2URL: Img22,
    name1: "Jerome Bell",
    name2: "Bessie Cooper",
    school: "Chicago",
  },
  {
    img1URL: Img23,
    img2URL: Img24,
    name1: "Marvin McKinney",
    name2: "Leslie Alexander",
    school: "MIT",
  },
  {
    img1URL: Img25,
    img2URL: Img26,
    name1: "Courtney Henry",
    name2: "Robert Fox",
    school: "Princeton",
  },
  {
    img1URL: Img27,
    img2URL: Img28,
    name1: "Jerome Bell",
    name2: "Bessie Cooper",
    school: "Chicago",
  },
  {
    img1URL: Img29,
    img2URL: Img30,
    name1: "Marvin McKinney",
    name2: "Leslie Alexander",
    school: "MIT",
  },
  {
    img1URL: Img31,
    img2URL: Img32,
    name1: "Courtney Henry",
    name2: "Robert Fox",
    school: "Princeton",
  },
  {
    img1URL: Img33,
    img2URL: Img34,
    name1: "Jerome Bell",
    name2: "Bessie Cooper",
    school: "Chicago",
  },
  {
    img1URL: Img35,
    img2URL: Img36,
    name1: "Marvin McKinney",
    name2: "Leslie Alexander",
    school: "MIT",
  },
  {
    img1URL: Img37,
    img2URL: Img38,
    name1: "Marvin McKinney",
    name2: "Leslie Alexander",
    school: "MIT",
  },
  {
    img1URL: Img39,
    img2URL: Img40,
    name1: "Marvin McKinney",
    name2: "Leslie Alexander",
    school: "MIT",
  },
  {
    img1URL: Img41,
    img2URL: Img42,
    name1: "Marvin McKinney",
    name2: "Leslie Alexander",
    school: "MIT",
  },
];
